version: '3.8'

services:
  cms-requisicoes:
    build: ./.docker
    container_name: cms-requisicoes
    restart: always
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3333:3333'
    networks:
      - db

networks:
  db:
    driver: bridge
    name: db
